name: master

on:
   push:
      paths-ignore:
         - 'doc/**'
         - '*.md'
      branches:
         - master

jobs:
   build:
      runs-on: ubuntu-latest

      strategy:
         matrix:
            product: [ "IC-241", "IC-242", "IC-243" ]
            include:
               -  product: "IC-241"
                  java: "17"
                  distribution: "temurin"
               -  product: "IC-242"
                  java: "17"
                  distribution: "temurin"
               -  product: "IC-243"
                  java: "17"
                  distribution: "temurin"
         max-parallel: 10
         fail-fast: false

      steps:
         -  uses: actions/checkout@v4
            with:
               fetch-depth: 0

         -  uses: actions/setup-java@v4
            with:
               java-version: ${{ matrix.java }}
               distribution: ${{ matrix.distribution }}

         -  name: Run tests
            run: ./gradlew check
            env:
               PRODUCT_NAME: ${{ matrix.product }}

         -  name: Bundle the build report
            if: failure()
            run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

         -  name: Upload the build report
            if: failure()
            uses: actions/upload-artifact@master
            with:
               name: error-report
               path: build-reports.zip

env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
