name: release

on:
   workflow_dispatch:

jobs:
   release:

      strategy:
         matrix:
            product: [ "IC-203", "IC-211", "IC-212", "IC-213", "IC-221", "IC-222" ]
         max-parallel: 1

      runs-on: ubuntu-latest

      steps:
         -  uses: actions/checkout@v3
            with:
               fetch-depth: 0

         -  uses: actions/setup-java@v3
            with:
               distribution: 'adopt'
               java-version: '11'

         -  name: deploy to jetbrains
            run: ./gradlew --stacktrace publishPlugin
            env:
               PRODUCT_NAME: ${{ matrix.product }}

env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
   JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}
