name: release

on:
   workflow_dispatch:

jobs:
   release:

      strategy:
         matrix:
            product: [ "IC-211", "IC-212", "IC-213", "IC-221", "IC-222", "IC-223", "IC-231" ]
         max-parallel: 1
         include:
            -  product: "IC-211"
               java: "11"
               distribution: "adopt"
            -  product: "IC-212"
               java: "11"
               distribution: "adopt"
            -  product: "IC-213"
               java: "11"
               distribution: "adopt"
            -  product: "IC-221"
               java: "11"
               distribution: "adopt"
            -  product: "IC-222"
               java: "11"
               distribution: "adopt"
            -  product: "IC-223"
               java: "17"
               distribution: "temurin"
            -  product: "IC-231"
               java: "17"
               distribution: "temurin"

      runs-on: ubuntu-latest

      steps:
         -  uses: actions/checkout@v3
            with:
               fetch-depth: 0

         -  uses: actions/setup-java@v3
            with:
               java-version: ${{ matrix.java }}
               distribution: ${{ matrix.distribution }}

         -  name: deploy to jetbrains
            run: ./gradlew --stacktrace publishPlugin
            env:
               PRODUCT_NAME: ${{ matrix.product }}

env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
   JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}
